# Generated by Django 4.2.26 on 2026-01-13 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
