# Generated by Django 4.2.26 on 2026-01-15 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('duration', models.IntegerField()),
                ('details', models.CharField(max_length=400)),
            ],
        ),
    ]
