# Generated by Django 4.2.26 on 2026-01-15 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemodel',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
